# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a7b3d46fdf528f6d98a41201a84ded9d16b22193a42073bb44bdc390860930c0950ae9e4a6f637fa2ee0b3676e9ae86b3766dac04ce65c2985c77b9b65537e4

test:
  secret_key_base: 928a4ecfd0a937719ccee9a540e13f70f37dd5438231cd17d6ee91fa00ab58033f266e6c43738f5a9faeccbabc582799b8061318e25d3c61ba1078dbabe6710e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
